-- liquibase formatted sql

-- changeset script:1
-- comment: Creation table clientes
create table clientes (
    id integer generated by default as identity,
    direccion varchar(255),
    identificacion integer not null,
    nombre varchar(255) not null,
    primary key (id)
);

-- changeset script:2
-- comment: Creation table envios
create table envios (
    id integer generated by default as identity,
    cantidad integer not null,
    descuento numeric(38,2),
    fecha_entrega timestamp(6) not null,
    fecha_registro timestamp(6) not null,
    numero_guia bigint not null,
    placa_flota varchar(255) not null,
    tipo_porducto varchar(255) not null,
    valor_envio numeric(38,2) not null,
    valor_neto numeric(38,2),
    id_cliente_fk integer not null,
    id_lugar_entrega_fk integer not null,
    id_tipo_envio_fk integer not null,
    primary key (id)
);

-- changeset script:3
-- comment: Creation table lugar_entrega
create table lugar_entrega (
    id integer generated by default as identity,
    nombre varchar(255),
    ubicacion varchar(255),
    primary key (id)
);

-- changeset script:4
-- comment: Creation table tipo_envios
create table tipo_envios (
    id integer generated by default as identity,
    nombre varchar(255),
    primary key (id)
);

-- changeset script:5
-- comment: Creation table usuarios
create table usuarios (
    id integer generated by default as identity,
    password varchar(255) not null,
    username varchar(255) not null,
    primary key (id)
);

-- changeset script:11
-- comment: Creation clientes
insert into clientes (direccion, identificacion, nombre) values
    ( 'Cali', 159357456, 'Camilo Cortez' );

-- changeset script:12
-- comment: Creation lugar_entrega
insert into lugar_entrega (nombre, ubicacion) values
    ( 'El estanco', 'Bogota' ),
    ( 'Deposito la 88', 'Barranquilla' ),
    ( 'Avenida 56', 'Meta' );

-- changeset script:13
-- comment: Creation tipo_envios
insert into tipo_envios (nombre) values
    ('Terrestre'),
    ('Maritimo');

-- changeset script:14
-- comment: Creation usuarios
insert into usuarios (password, username) values
    ( '$2a$10$P7GVulAKtvA.AB96yTZeJe51r.eHVvk2nFNdX9Kmv/6Z6MZyy96.e', 'user' );

-- changeset script:15
-- comment: Creation envios
insert into envios (cantidad, id_cliente_fk, descuento, fecha_entrega, fecha_registro, id_lugar_entrega_fk, numero_guia,
                    placa_flota, id_tipo_envio_fk, tipo_porducto, valor_envio, valor_neto) values
    (10, 1, 0, '2024-01-21 00:00:00', '2024-01-20 09:00:00', 1, 9632587410 , 'cto301', 1, 'Juguete', 1000.00 ,1000.00);