spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/logistica
    username : postgres
    password: admin

logging:
  level:
    com:
      client: INFO
server:
  port: 8080
#springdoc:
#  swagger-ui:
#    path=/swagger-ui:
#      html: /swagger-ui.html
